### PR TITLE
Update for stable 1.0

### PR DESCRIPTION
**Pull request by davwheat**
- Updates for Stable 1.0
- Adds new extension table to Flarum data

I still can't get Clockwork showing data on the initial page load and have no clue what is missing. Anyone else have any ideas about what I'm missing?

### CODE REVIEW

**Comment by luceos** [comment]
I traced it to the headers. `vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/Clockwork.php` has a `sendHeaders` method. None of those are added to the response, the `Server-Timing` from line `80` is.. Initially they are added though, but in the eventual output they are dropped.

**Review by imorland — APPROVED** [review]

**Comment by datitisev** [comment]
> I still can't get Clockwork showing data on the initial page load and have no clue what is missing. Anyone else have any ideas about what I'm missing?

Was this fixed then?

**Comment by imorland** [comment]
I tested earlier today, and all was good. Not sure if it was a local issue maybe that @davwheat was experiencing?

**Comment by datitisev** [comment]
Isn't Daniel's comment about it as well?

**Pull request merged**
